/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminAuth: () => import('#controllers/admin_auth_controller'),
  Admin: () => import('#controllers/admin_controller'),
  Invitation: () => import('#controllers/invitation_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
