/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GallerySchema extends BaseModel {
  static $columns = ['caption', 'createdAt', 'id', 'imageUrl', 'invitationId', 'sortOrder', 'updatedAt'] as const
  $columns = GallerySchema.$columns
  @column()
  declare caption: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string
  @column()
  declare invitationId: number
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GuestSchema extends BaseModel {
  static $columns = ['attendance', 'comment', 'createdAt', 'id', 'invitationId', 'name', 'updatedAt'] as const
  $columns = GuestSchema.$columns
  @column()
  declare attendance: string | null
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitationId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvitationSchema extends BaseModel {
  static $columns = ['akadDatetime', 'bankAccountHolder', 'bankAccountNumber', 'bankName', 'bgMusicUrl', 'brideName', 'brideNickname', 'brideParentFather', 'brideParentMother', 'createdAt', 'eventAddress', 'eventLocation', 'googleMapsUrl', 'groomName', 'groomNickname', 'groomParentFather', 'groomParentMother', 'id', 'resepsiDatetime', 'slug', 'style', 'updatedAt', 'walletHolder', 'walletName', 'walletNumber'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare akadDatetime: DateTime
  @column()
  declare bankAccountHolder: string | null
  @column()
  declare bankAccountNumber: string | null
  @column()
  declare bankName: string | null
  @column()
  declare bgMusicUrl: string | null
  @column()
  declare brideName: string
  @column()
  declare brideNickname: string
  @column()
  declare brideParentFather: string | null
  @column()
  declare brideParentMother: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventAddress: string
  @column()
  declare eventLocation: string
  @column()
  declare googleMapsUrl: string | null
  @column()
  declare groomName: string
  @column()
  declare groomNickname: string
  @column()
  declare groomParentFather: string | null
  @column()
  declare groomParentMother: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare resepsiDatetime: DateTime
  @column()
  declare slug: string
  @column()
  declare style: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare walletHolder: string | null
  @column()
  declare walletName: string | null
  @column()
  declare walletNumber: string | null
}

export class StorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'imageUrl', 'invitationId', 'milestoneDate', 'sortOrder', 'title', 'updatedAt'] as const
  $columns = StorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare invitationId: number
  @column()
  declare milestoneDate: string
  @column()
  declare sortOrder: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
